web: python -c "import nltk; nltk.download('vader_lexicon', quiet=True)" && alembic upgrade head && gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
worker: celery -A app.tasks.celery_app:celery_app worker --loglevel=info --concurrency=2
