"""initial_tables

Revision ID: 72e7ed43351d
Revises: 
Create Date: 2026-02-27 13:34:06.176652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e7ed43351d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='cs_engineer', nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('cs_owner_id', sa.Uuid(), nullable=True),
    sa.Column('deployment_mode', sa.String(length=50), server_default='OVA', nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('integrations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('known_constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cs_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_cs_owner', 'customers', ['cs_owner_id'], unique=False)
    op.create_index('idx_customers_renewal', 'customers', ['renewal_date'], unique=False)
    op.create_index('idx_customers_tier', 'customers', ['tier'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actions_customer', 'action_items', ['customer_id'], unique=False)
    op.create_index('idx_actions_deadline', 'action_items', ['deadline'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_actions_owner', 'action_items', ['owner_id'], unique=False)
    op.create_index('idx_actions_status', 'action_items', ['status'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_agent_date', 'agent_logs', ['agent_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_agent_logs_customer', 'agent_logs', ['customer_id'], unique=False)
    op.create_index('idx_agent_logs_status', 'agent_logs', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('similar_past_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=True),
    sa.Column('slack_notified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_customer', 'alerts', ['customer_id'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('call_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('fathom_recording_id', sa.String(length=255), nullable=True),
    sa.Column('call_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('customer_recap_draft', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_customer_date', 'call_insights', ['customer_id', sa.literal_column('processed_at DESC')], unique=False)
    op.create_index('idx_insights_sentiment', 'call_insights', ['sentiment'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('routed_to', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_date', 'events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('idx_events_type', 'events', ['event_type'], unique=False)
    op.create_table('health_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_health_score_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_customer_date', 'health_scores', ['customer_id', sa.literal_column('calculated_at DESC')], unique=False)
    op.create_index('idx_health_risk_level', 'health_scores', ['risk_level'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_customer', 'reports', ['customer_id'], unique=False)
    op.create_index('idx_reports_date', 'reports', [sa.literal_column('generated_at DESC')], unique=False)
    op.create_index('idx_reports_type', 'reports', ['report_type'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jira_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('triage_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('troubleshoot_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id')
    )
    op.create_index('idx_tickets_assigned', 'tickets', ['assigned_to_id'], unique=False)
    op.create_index('idx_tickets_customer', 'tickets', ['customer_id'], unique=False)
    op.create_index('idx_tickets_jira', 'tickets', ['jira_id'], unique=False)
    op.create_index('idx_tickets_severity', 'tickets', ['severity'], unique=False)
    op.create_index('idx_tickets_sla', 'tickets', ['sla_deadline'], unique=False, postgresql_where=sa.text("status NOT IN ('resolved', 'closed')"))
    op.create_index('idx_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_status', table_name='tickets')
    op.drop_index('idx_tickets_sla', table_name='tickets', postgresql_where=sa.text("status NOT IN ('resolved', 'closed')"))
    op.drop_index('idx_tickets_severity', table_name='tickets')
    op.drop_index('idx_tickets_jira', table_name='tickets')
    op.drop_index('idx_tickets_customer', table_name='tickets')
    op.drop_index('idx_tickets_assigned', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_reports_type', table_name='reports')
    op.drop_index('idx_reports_date', table_name='reports')
    op.drop_index('idx_reports_customer', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_health_risk_level', table_name='health_scores')
    op.drop_index('idx_health_customer_date', table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_date', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_insights_sentiment', table_name='call_insights')
    op.drop_index('idx_insights_customer_date', table_name='call_insights')
    op.drop_table('call_insights')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_customer', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_agent_logs_status', table_name='agent_logs')
    op.drop_index('idx_agent_logs_customer', table_name='agent_logs')
    op.drop_index('idx_agent_logs_agent_date', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_actions_status', table_name='action_items')
    op.drop_index('idx_actions_owner', table_name='action_items')
    op.drop_index('idx_actions_deadline', table_name='action_items', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_actions_customer', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('idx_customers_tier', table_name='customers')
    op.drop_index('idx_customers_renewal', table_name='customers')
    op.drop_index('idx_customers_cs_owner', table_name='customers')
    op.drop_table('customers')
    op.drop_table('users')
    # ### end Alembic commands ###
